version: '3.8'

services:
  spring-boot-demo:
    build:
      context: .
      dockerfile: Dockerfile
    image: spring-boot-demo:latest
    container_name: spring-boot-demo
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xms256m -Xmx512m
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/hello"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s